### ISSUE TITLE
No shared internet or WiFI 

### ISSUE THREAD

**Issue by jbiams77** [strath-sdr/rfsoc_sam#4]
I'm currently working with your Pynq image 2.6 and have successfully implemented the rfsoc_qpsk build. I'm wanting to implement the rfsoc_sam but my ZCU111 does not have a WiFi dongle and I am unable to create a shared internet connection. As a result, the I cannot do a pip3 install of the repository, is there a PYNQ image containing this build already on it like the rfsoc_qpsk? Or, is there a way to target the ZCU111 with the bitstream?

**Comment by jbiams77** [comment]
I was able to use the bitsream directly and display within notebook not using the ZCU111

**Comment by dnorthcote** [comment]
Hi @jbiams77 ,

Apologies for the late response. You can pip install if you clone the github repository to the board.  Follow the instructions below to install the Spectrum Analyser when the board isn't connected to the internet.

## **Offline Installation of the Spectrum Analyser**

* Obtain a zipped copy of the repository.

![image](https://user-images.githubusercontent.com/42978178/108706727-ef4d3480-7506-11eb-81a1-0ae3c2748130.png)

* Move this zip file into your Jupyter Workspace by simply dragging it into your browser window from the file explorer.

![image](https://user-images.githubusercontent.com/42978178/108707010-5b2f9d00-7507-11eb-8609-8e5a9bcb1bd5.png)

* Then simply unzip the file by running the command below in a terminal:

`unzip /home/xilinx/jupyter_notebooks/rfsoc_sam-master.zip -d /home/xilinx/jupyter_notebooks/rfsoc_sam-master`

* A new folder will be created name rfsoc_sam-master. Lets change directory into this folder from the terminal:

`cd /home/xilinx/jupyter_notebooks/rfsoc_sam-master/rfsoc_sam-master`

* Lastly we can call pip to install the spectrum-analyser.

`pip3 install .`

## **Offline ZCU111 xrfdc Patch**

* We also need to patch the xrfdc package. To do this navigate to this [repository](https://github.com/dnorthcote/ZCU111-PYNQ) and obtain a zip download.

* As before, copy the zip file into Jupyter workspace  and unzip its contents using the command below in a terminal:

`unzip /home/xilinx/jupyter_notebooks/ZCU111-PYNQ-master.zip -d /home/xilinx/jupyter_notebooks/ZCU111-PYNQ-master`

* Finally, run the following script in terminal which will patch the xrfdc package.

```
cd /home/xilinx/jupyter_notebooks/ZCU111-PYNQ-master/ZCU111-PYNQ-master
cp ./ZCU111/packages/xrfdc/pkg/xrfdc/__init__.py /usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py
```
